// <auto-generated />
namespace PAYG_Payroll.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class company1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(company1));
        
        string IMigrationMetadata.Id
        {
            get { return "201504142251270_company1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
